name: Lint and Static Analysis

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gdscript-lint:
    name: GDScript Linting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Download Godot 4.4
      run: |
        cd /tmp
        wget -q https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_linux.x86_64.zip
        unzip -q Godot_v4.4-stable_linux.x86_64.zip
        chmod +x Godot_v4.4-stable_linux.x86_64
        mv Godot_v4.4-stable_linux.x86_64 /tmp/godot

    - name: Install gdtoolkit (contains gdformat)
      run: |
        pip install gdtoolkit

    - name: Install editorconfig-checker
      run: |
        cd /tmp
        wget -q https://github.com/editorconfig-checker/editorconfig-checker/releases/latest/download/ec-linux-amd64.tar.gz
        tar -xzf ec-linux-amd64.tar.gz
        chmod +x bin/ec-linux-amd64

    - name: Check EditorConfig compliance
      run: |
        echo "Checking EditorConfig compliance..."
        # Exclude binary files, assets, and generated content
        if ! /tmp/bin/ec-linux-amd64 -exclude "\.godot|\.git|\.import|\.zip$|\.blend$|\.blend1$|\.fbx$|\.material$|\.tscn$|\.tres$|bin/"; then
          echo "❌ Some files do not comply with EditorConfig settings."
          echo "Note: This mainly affects GDScript files. Run 'gdformat .' to fix most issues."
          exit 1
        else
          echo "✅ All files comply with EditorConfig settings."
        fi

    - name: Validate project configuration
      run: |
        # Import assets
        /tmp/godot --headless --import --verbose

        # Test if main scene loads without errors
        echo "Testing main scene load..."
        if /tmp/godot --headless --path . "res://Stages/Game/main/main.tscn" --quiet; then
          echo "✅ Main scene loads successfully"
        else
          echo "❌ Main scene failed to load"
          exit 1
        fi

    - name: Check formatting
      run: |
        echo "Checking GDScript file formatting..."
        # Check if any files need formatting
        if ! gdformat --check --diff .; then
          echo "❌ Some files are not properly formatted."
          echo "Run 'gdformat .' to fix formatting issues."
          exit 1
        else
          echo "✅ All files are properly formatted."
        fi

    - name: Run linting
      run: |
        echo "Running GDScript linter..."
        gdlint . > gdlint_report.txt || true
        if grep -q "error:" gdlint_report.txt; then
          echo "❌ Linting issues found."
          cat gdlint_report.txt
          echo "::warning file=gdlint_report.txt::Linting issues detected. See above for details."
        else
          echo "✅ No linting issues found."
        fi
