name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Cache Godot import files
      uses: actions/cache@v4
      with:
        path: .godot/
        key: godot-import-${{ hashFiles('**/*.gd', '**/*.tscn', '**/*.tres', 'project.godot') }}
        restore-keys: |
          godot-import-
    
    - name: Download Godot
      run: |
        wget -q https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_linux.x86_64.zip
        unzip -q Godot_v4.4-stable_linux.x86_64.zip
        chmod +x Godot_v4.4-stable_linux.x86_64
        mv Godot_v4.4-stable_linux.x86_64 ./godot
        ./godot --version
    
    - name: Import project files
      run: |
        # Only run full import if .godot directory is not cached
        if [ ! -d ".godot/imported" ]; then
          echo "Running initial project import (this may take 15+ minutes)..."
          timeout 1200 ./godot --headless --import --path . || echo "Import completed or timed out"
        else
          echo "Using cached import files"
        fi
    
    - name: Run Tests
      run: |
        ./run_tests.sh
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          .godot/
        retention-days: 7
