name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Download Godot
      run: |
        wget -q https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_linux.x86_64.zip
        unzip -q Godot_v4.4-stable_linux.x86_64.zip
        chmod +x Godot_v4.4-stable_linux.x86_64
        mv Godot_v4.4-stable_linux.x86_64 ./godot
        ./godot --version
    
    - name: Import Assets
      run: |
        # Quick import to register scripts and plugins
        timeout 60 ./godot --headless --quit --path . || true
    
    - name: Run Tests
      run: |
        ./run_tests.sh
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          .godot/
        retention-days: 7
